var randomArray = [
    'Alligator','Anteater','Bear'
    ,'Bird','Bull','Cat'
    ,'Chicken','Cow','Cub'
    ,'Deer','Dog','Duck'
    ,'Eagle','Elephant','Frog'
    ,'Goat','Gorilla','Hamster'
    ,'Hippo','Horse','Kangaroo'
    ,'Koala','Lion','Monkey'
    ,'Mouse','Octopus','Ostrich'
    ,'Penguin','Pig','Rabbit'
    ,'Rhino','Sheep','Squirrel'
    ,'Tiger','Wolf'
];

var personalities =[
    'Sisterly'
    ,'Snooty'
    ,'Cranky'
    ,'Smug'
    ,'Peppy'
    ,'Normal'
    ,'Lazy'
    ,'Jock'
    ];

var styles =[
    'Sporty', 'Cute', 'Iconic', 'RocknRoll', 'Official'
    , 'Ornate', 'Flashy', 'Modern', 'Historical', 'Basic'
];

//http://www.animalcrossingcommunity.com/Topic/4468132/1/Villagers_catchphrase_List
catchphr =[
    ,'Tubby/tubbo'
    ,'chubby/chubbo'
    ,'Buddy/buddy boy'
    ,'chimp/chimpy/chimpet'
    , 'Honey,hunny'
    ,'Neighbor'
    ,'Corn hole'
    ,'Comrad'
    ,'Boss'
    ,'sly'
    ,'slick'
    ,'Hot stuff'
    ,'Snowflake'
    ,'Bear'
    ,'Puddin pop'
    ,'Show off'
    ,'Cub'
    ,'baby'
    ,'idiot'
    ,'Colt'
    ,'Pup/puppy'
    ,'Kitten'
    ,'Shrimp'
    ,'Smarty'
    ,'Calf'
    ,'dummy'
    ,'Sweetie'
    ,'Nice guy/Nice girl'
    ,'Mate'
    ,'Sweet heart'
    ,'sugar'
    ,'My friend'
    ,'Angle'
    ,'Pumpkin'
    ,'Dude/Dood'
    ,'Queen'
    ,'Snow angle'
    ,'bum'
    ,'man'
    ,'punk'
    ,'Bacon'
    ,'Chocolate'
    ,'Caramel'
    ,'Hick/Hicker'
    ,'Icy'
    ,'Sonny'
    ,'Dog'
    ,'Goofball'
    ,'Clown'
    ,'Nerd'
    ,'Hill billy'
    ,'Captain'
    ,'Swindler'
    ,'Poser'
    ,'Phony'
    ,'Derr'
    ,'Honey bun'
    ,'Boy'
    ,'girl'
    ,'Frosting'
    ,'Monster'
    ,'Icing'
    ,'Emerald'
    ,'Kitty cat'
    ,'Handsome'
    ,'Pertty'
    ,'Squeaker'
    ,'Smelly'
    ,'Piggy'
    ,'fatso'
    ,'Sneaky'
    ,'Tiny'
    ,'Prince'
    ,'Princess'
    ,'Greaser'
    ,'Hoe'
    ,'Cookie'
    ,'Muffin'
    ,'Peanut'
    ,'coco'
    ,'flower'
    ,'Noob'
    ,'cup cake'
    ,'Dead weight'
    ,'Meat bag'
    ,'Girl friend'
    ,'Smiggs'
    ,'Bro'
    ,'sis'
    ,'Hooser'
    ,'Pal'
    ,'Work horse'
    ,'B-B-buddy'
    ,'Foxy'
    ,'ace'
    ,'Bender'
    ,'soul mate'
    ,'Smoker'
    ,'Joker'
    ,'Speedy'
    ,'hero'
    ,'Its a mii'
    ,'Mother'
    ,'Father'
    ,'Killer'
];